global using Microsoft.EntityFrameworkCore;
global using PiggyBank.Data;
global using PiggyBank.Data.Models;
global using PiggyBank.Data.Services;
global using PiggyBank.Helpers;
global using System;
global using System.Collections.ObjectModel;
global using System.Collections.Specialized;
global using System.ComponentModel.DataAnnotations;