require_relative "amortization"
require_relative "formatter"
require_relative "tax/form/adapter/us/form_1040"
require_relative "tax/form/adapter/us/sched_1"
require_relative "tax/form/adapter/us/sched_e"
require_relative "tax/form/writer/us/form_1040"
require_relative "tax/form/writer/us/sched_1"
require_relative "tax/form/writer/us/sched_e"
