"""Add Account and Commodity tables

Revision ID: 21dc81614120
Revises: 
Create Date: 2021-05-27 12:41:03.905646

"""
from alembic import op
import sqlalchemy as sa
from server.models.account import Account, AccountType
from server.models.commodity import Commodity, CommodityType

# revision identifiers, used by Alembic.
revision = "21dc81614120"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "ASSET",
                "EQUITY",
                "EXPENSE",
                "INCOME",
                "LIABILITY",
                "MORTGAGE",
                name="accounttype",
            ),
            nullable=False,
        ),
        sa.Column("commodity_id", sa.Integer(), nullable=False),
        sa.Column("is_placeholder", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "commodity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "commodity_type",
            sa.Enum("CURRENCY", "INVESTMENT", name="commoditytype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("ticker", sa.String(length=256), nullable=True),
        sa.Column("fraction", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    usd = Commodity(
        commodity_type=CommodityType.CURRENCY,
        description="US Dollar",
        fraction=100,
        name="USD",
        ticker="USD",
    )
    session.add(usd)
    session.commit()

    base_accounts = [
        ("Assets", AccountType.ASSET),
        ("Liabilities", AccountType.LIABILITY),
        ("Equity", AccountType.EQUITY),
        ("Income", AccountType.INCOME),
        ("Expense", AccountType.EXPENSE),
    ]

    for (name, account_type) in base_accounts:
        account = Account(
            name=name,
            account_type=account_type,
            is_placeholder=True,
            commodity_id=usd.id,
        )
        session.add(account)

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("commodity")
    op.drop_table("account")
    # ### end Alembic commands ###
